### ISSUE TITLE
feature request and some bugs found

### ISSUE THREAD

**Issue by darkr4y** [jephthai/EvilVM#1]
First of all,thanks for such an excellent project

in the code review and test, I found some bugs:
1. ls command wont reply the file list
2. no error handler for the agent when connection lost

and I found that the http communication was encrypted, but TCP did not.I think TCP communication encryption is also necessary,but I am not very good at assembly programming.

I would like to express my sincere gratitude and thx for providing such a good project for researching and learning ;)

**Comment by jephthai** [comment]
Thanks for feedback. The `ls` command requires an argument, and if you don't supply one it's call to `readline` will still be waiting for the path/glob to list. If you want a no argument listing (current directory) use `dir` for now. I've been thinking of adding some control code notation so the server can tell you there's an empty readline... not sure yet how to handle that. 

Lost connections are a good catch. I'll make a note to add some basic recovery (exit or reconnect?) on connection loss. 

And yes, the TCP transport existed before I added crypto. I'd actually like to make crypto modular and configurable for all transports. It does increase payload size substantially (about a kilobyte I think), so I really want it to be optional.

**Comment by jephthai** [comment]
OK, I pushed a quick stab at adding crypto to the TCP transport in commit fba57b9.  It can be configured with the build command by passing the `-c` option, e.g.:

    $ ./build.rb -n 192.168.4.3 -p 1922 -c -E -o tcpcrypt.exe

To use it, there's now a `tcpcrypt` shim, which you can run from the `server/` directory.  That will listen on 1922 by default, and proxy sessions to the standard server.  I'm trying as much as I can to keep the server simple, so I think shimming the encrypted TCP session is reasonable -- let me know if you don't think that's a good idea.

**Comment by darkr4y** [comment]
Just tested, reply now.

Its a very great idea about proxy sessions,I do get your design goals. Its more like CobaltStrike [ExternalC2](https://www.cobaltstrike.com/downloads/externalc2spec.pdf), but on the agent side,if I want to add an encrypted transport layer by writing code myself,the way to directly modify the agent's assembly code is not so elegant. yeah In fact, what I want to say is that if you can add IO method which using named pipe, in that way programmers who often use C language programming like me can  interact with the agent by writing their own code. the idea is come from CobaltStrike's External C2, you may be able to think about it.

and forgive my stupid, will never understand how to use `ls` command, I tried

```
1  [spring-green]  -> pwd
1  [spring-green]  ->
---- BEGIN OUTPUT ----
c:\
----- END OUTPUT -----
1  [spring-green]  -> ls c:\
1  [spring-green]  -> Error! 2

1  [spring-green]  -> ls C:\
1  [spring-green]  -> Error! 2
```

another little suggestion, I found that the `download` command has been implemented. Why not provide `upload` command? The `upload` command should implement two functions. One is to transfer local data to a remote disk, and the other is to transfer local data to remote memory.so I can try to write plugins using Reflective Dll and run it in memory with `upload` command and also upload a file to remote. The `load` command now is only for the forth language, which limits the extension of the functionality in some how.

the last, have a good day and good health :)

**Comment by jephthai** [comment]
Ah, now I see what's happening with the `ls` command -- it's based on the Win32 `FindFirstFile` and `FindNextFile` functions, and they require a glob to enumerate contents of a directory.  If you do this, it should work fine:

    1  [sea-green]  -> ls c:\*
    1  [sea-green]  -> 
    ---- BEGIN OUTPUT ----
    2016-12-18 21:30:13.480                0 $Recycle.Bin/
    2016-07-16 11:43:00.546           384322 bootmgr
    2016-07-16 11:43:00.546                1 BOOTNXT
    . . .
    2019-05-15 20:55:40.885                0 temp/
    2018-07-17 17:14:09.420                0 Users/
    2019-06-08 06:34:35.511                0 Windows/
    ----- END OUTPUT -----
    1  [sea-green]  -> 

Maybe it should check if the last character is a `\` or `/` and tack on a `*`, since that is likely the preferred behavior.

**Comment by jephthai** [comment]
Regarding transports, it is a consequence of design that transport code has to be written in assembly.  There are transport options that could provide interfacing with other transport code, if you wanted to play with transports in a higher level language.  E.g., the `memio` transport uses shared memory to transmit bytes in and out.  Also, connecting stdin/stdout through pipes to another program to drive the transport would be possible with the standard streams transport.

A named pipe transport is also on the list.  I just finished rev1 on ICMP, and next will be UDP and named pipes.  This week I was playing with the `ruby_smb` library, which seems like it'll work great for a shim on the server side to connect out to a named pipe.  Of course, once the agent can listen on a named pipe, anything can connect to it and proxy the comms however it wants.

And regarding `download` and `upload` -- yeah, I definitely intend to do both, and in a better way too.  After implementing the `seeasm` function (where I added a way for the agent to tell the server that some number of bytes should be interpreted differently from standard output), I realized I can use the same design for downloading files.  Uploading will be a server console command (something like `^Kupload <file>`).  Definitely on the list.

**Comment by jephthai** [comment]
It's been awhile on this (wow!), but some of this is certainly done.  E.g., there are some new transports, etc.  I'm going to close this issue for now, as I don't think there are any outstanding tasks I want to pursue emanating from this discussion.
