### ISSUE TITLE
Error when trying create an agent

### ISSUE THREAD

**Issue by oz17il** [jephthai/EvilVM#5]
Hi, 

From the EvilVM directory, I run the "build.rb" script to generate a new agent:
`./build.rb -n -i $server -p 443 -E -o agent.exe`

In the background the "server.rb" is running but I still get an error:

```
root@ubuntu-s:~/EvilVM# ./build.rb -n -i $server -p 443 -E -o agent.exe
IP: -p
/tmp/object20210413-1712-1abst77: file not recognized: File truncated
Traceback (most recent call last):
        3: from ./build.rb:421:in `<main>'
        2: from ./build.rb:161:in `compile'
        1: from ./build.rb:150:in `link'
./build.rb:150:in `read': No such file or directory @ rb_sysopen - /tmp/binary20210413-1712-80hf4l (Errno::ENOENT)
```

Please your help

Ubuntu 18
ruby 2.7

**Comment by jephthai** [comment]
Is there any chance that you don't have `nasm` installed on your system?  When I remove `nasm` from my path, I get the same error message, so perhaps that is it.  If `which nasm` doesn't turn anything up, though, let me know, and we can perhaps add some trace statements and see what else might be going on.

**Comment by jephthai** [comment]
OK, it's been a few days -- I'm going to assume that a missing `nasm` was the issue, or that you've resolved the issue somehow.  If not, feel free to reply again, and I'll be more than happy to help debug your situation.  Thanks!
