### ISSUE TITLE
Docs is down

### ISSUE THREAD

**Issue by TG9541** [jephthai/EvilVM#6]
The docs appear to have dropped off of the internet. Would you bringing them back up? 

The repo's GitHub wiki is maybe be a good place but a an archive from the original docs site would be sufficient.

Thanks!

**Comment by jephthai** [comment]
Wow, I didn't realize that expired.  I just renewed it, should be back up soon.  And yeah, I probably should at least copy all the docs to the repo.  Thanks for letting me know!
